### Required params
input: "/exports/archive/lucid-grpzeller-primary/hackett/EBI_Project/results/2024-04-01/fetched_pdbs.list" # required, path-string
output: "/exports/archive/lucid-grpzeller-primary/hackett/EBI_Project/data/2024-04-23/results.tsv" # required, path-string
batch_size: 250 # required, integer

### Optional params
template_folder: "" # optional, path-string

### Optional Jess parameters
# rmsd: 2.0 # optional, float
# distance: 1.5 # optional, float
# max_dynamic_distance: 1.5 # optional, float
# conservation_cutoff: 0 # optional, float

#### Optional flag paramters
warn: False # optional, boolean
verbose: True # optional, boolean
unfiltered: False # optional, boolean
match_small_templates; False # optional, boolean
skip_smaller_hits: False # optional, boolean
skip_annoation: False # optional, boolean
n_cpus: -1 # optional, default 0 (all but two threads), negative numbers thread all cpus, positve number is explicit
