name: Apptainer

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    # # Use the official Apptainer container for convenience
    # container:
    #     image: ghcr.io/apptainer/apptainer:1.4.2
    #     options: --privileged --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update -y
          sudo apt-get install -y apptainer

      - name: Extract version from tag
        id: get_tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Apptainer image
        run: |
          apptainer build enzymm.sif enzymm_apptainer.def

      - name: Upload SIF to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: enzymm.sif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install ORAS CLI
        run: |
          mkdir -p $HOME/.local/bin
          export PATH=$HOME/.local/bin:$PATH
          # sudo apt-get install -y wget
          wget -qO- https://github.com/oras-project/oras/releases/download/v1.2.0/oras_1.2.0_linux_amd64.tar.gz \
            | tar -xvz -C $HOME/.local/bin

      - name: Push with ORAS
        run: |
          export PATH=$HOME/.local/bin:$PATH

          oras push ghcr.io/${{ github.repository }}:${{ steps.get_tag.outputs.version }} \
            --artifact-type application/vnd.sylabs.sif.layer.v1 \
            enzymm.sif:application/vnd.sylabs.sif.layer.v1

          oras push ghcr.io/${{ github.repository }}:latest \
            --artifact-type application/vnd.sylabs.sif.layer.v1 \
            enzymm.sif:application/vnd.sylabs.sif.layer.v1

      # - name: Login to GHCR
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.repository_owner }} --password-stdin oras://ghcr.io

      # - name: Push Apptainer image to GHCR
      #   run: |
      #     apptainer push enzymm.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${{ steps.get_tag.outputs.version }}
      #     apptainer push enzymm.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
