name: Apptainer

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    # # Use the official Apptainer container for convenience
    # container:
    #     image: ghcr.io/apptainer/apptainer:1.4.2
    #     options: --privileged --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update -y
          sudo apt-get install -y apptainer

      - name: Extract version from tag
        id: get_tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Apptainer image
        run: |
          apptainer build enzymm.sif enzymm_apptainer.def

      - name: Upload SIF to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: enzymm.sif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Apptainer image to GHCR
        run: |
          apptainer push enzymm.sif oras://ghcr.io/rayhackett/enzymm:${{ steps.get_tag.outputs.version }}
          apptainer push enzymm.sif oras://ghcr.io/rayhackett/enzymm:latest
