name: Docker

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for GHCR
      id-token: write  # Required for OIDC authentication

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VERSION=${{ steps.get_tag.outputs.version }} \
            -t ghcr.io/${{ github.repository_owner }}/enzymm:latest \
            -t ghcr.io/${{ github.repository_owner }}/enzymm:${{ steps.get_tag.outputs.version }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/enzymm:latest
          docker push ghcr.io/${{ github.repository_owner }}/enzymm:${{ steps.get_tag.outputs.version }}